<%@ Page Title="" Language="C#" MasterPageFile="~/Admin/AdminMaster.Master" AutoEventWireup="true" CodeBehind="Orders.aspx.cs" Inherits="ProjectKJ.Admin.Orders" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <div class="auto-style1">
        <h2>Order Details</h2>
        <asp:GridView ID="GridView1" runat="server" AllowPaging="True" AutoGenerateColumns="False" CellPadding="4" DataKeyNames="order_id" DataSourceID="SqlDataSource1" Height="130px" Width="210px" ForeColor="#333333" GridLines="None" HorizontalAlign="Center" ShowFooter="True" CssClass="table table-hover table-bordered" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True">
            <AlternatingRowStyle BackColor="White" />
            <Columns>
                <asp:BoundField DataField="order_id" HeaderText="Order ID" SortExpression="order_id" InsertVisible="False" ReadOnly="True" />
                <asp:BoundField DataField="customer_name" HeaderText="Name" SortExpression="customer_name" />
                <asp:BoundField DataField="customer_email" HeaderText="Email" SortExpression="customer_email" />
                <asp:BoundField DataField="customer_mobile" HeaderText="Mobile" SortExpression="customer_mobile" />
                <asp:BoundField DataField="customer_address" HeaderText="Address" SortExpression="customer_address" />
                <asp:BoundField DataField="customer_city" HeaderText="City" SortExpression="customer_city" />
                <asp:BoundField DataField="customer_price" HeaderText="Price" SortExpression="customer_price" />
                <asp:BoundField DataField="customer_order_date" HeaderText="Order Date" SortExpression="customer_order_date" />
            </Columns>
            <EditRowStyle BackColor="#7C6F57" />
            <FooterStyle BackColor="#1C5E55" ForeColor="White" Font-Bold="True" />
            <HeaderStyle BackColor="#1C5E55" Font-Bold="True" ForeColor="White" />
            <PagerStyle BackColor="#666666" ForeColor="White" HorizontalAlign="Center" />
            <RowStyle BackColor="#E3EAEB" />
            <SelectedRowStyle BackColor="#C5BBAF" Font-Bold="True" ForeColor="#333333" />
            <SortedAscendingCellStyle BackColor="#F8FAFA" />
            <SortedAscendingHeaderStyle BackColor="#246B61" />
            <SortedDescendingCellStyle BackColor="#D4DFE1" />
            <SortedDescendingHeaderStyle BackColor="#15524A" />
        </asp:GridView>
        <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:Manager_AnQDBConnectionString %>" UpdateCommand="UPDATE [tbl_customer_order] Set [customer_name]=@customer_name, [customer_mobile]=@customer_mobile, [customer_email]=@customer_email, [customer_address]=@customer_address, [customer_city]=@customer_city, [customer_price]=@customer_price Where [order_id]=@order_id" DeleteCommand="DELETE From [tbl_customer_order] where [order_id]=@order_id" SelectCommand="SELECT [customer_order_date], [customer_price], [customer_city], [customer_address], [customer_email], [customer_name], [customer_mobile], [order_id] FROM [tbl_customer_order]"></asp:SqlDataSource>
    </div>
</asp:Content>
